(function () {
  var ROOM = "eceebae";
  var API = "https://extendsclass.com/api/json-storage/bin/";
  var CANONICAL = "https://loveudonald-sys.github.io/soohum/sadari.html";
  var AV = { "송현":"🦊", "서니":"🌻", "인원":"🐻", "소아":"🐱", "강수":"🌊", "승진":"⚡" };
  var COLORS = ["#ff4d8f","#ffd36b","#6ef0c4","#7ec8ff","#ff9a62","#d9a5ff","#fff","#9dff6e"];
  var soundOn = true;
  var isAdmin = false;
  var me = localStorage.getItem("sadari_me") || "";
  var remoteOk = true;
  var riding = false;
  var state = defaultState();
  function defaultState(){return {v:1,title:"사다리고고",pin:"0326",players:["송현","서니","인원","소아","강수","승진"],days:["일","월","화","수","목","금"],buildings:["","","","","",""],ready:false,l1:null,l2:null,results:{},rev:1,updatedAt:0};}
  function $(id){return document.getElementById(id);}
  function toast(msg){var t=$("toast");t.textContent=msg;t.classList.add("on");setTimeout(function(){t.classList.remove("on");},1800);}
  function splitList(s){return (s||"").split(/[,|\n]/).map(function(x){return x.trim();}).filter(Boolean);}
  function hashRoom(){var h=(location.hash||"").replace(/^#/,"");if(!h)return;var m=h.match(/(?:^|&)?r=([a-z0-9]+)/i);ROOM=m?m[1]:h.split("&")[0].split("=").pop();}
  function shareUrl(){var here=(location.protocol==="https:"&&location.hostname)?(location.origin+location.pathname):CANONICAL;return here+"#r="+ROOM;}
  function localKey(){return "sadari_v2_"+ROOM;}
  function readLocal(){try{return JSON.parse(localStorage.getItem(localKey())||"null");}catch(e){return null;}}
  function writeLocal(){try{localStorage.setItem(localKey(),JSON.stringify(state));}catch(e){}}
  function avatar(name){return AV[name]||"🎲";}
  function doneCount(){var n=0;state.players.forEach(function(p){if(state.results[p]&&state.results[p].day)n++;});return n;}
  function isReady(){return !!(state.ready&&state.l1&&state.l2&&state.buildings.every(function(b){return String(b).trim();}));}
  function rng(seed){var s=(seed>>>0)||1;return function(){s=(Math.imul(s,1664525)+1013904223)>>>0;return s/4294967296;};}
  function makeLadder(n,rows,seed){var r=rng(seed),rungs=[],i,row,k;for(k=0;k<rows;k++){row=[];for(i=0;i<n-1;i++){if(i>0&&row[i-1])row.push(false);else row.push(r()<0.48);}rungs.push(row);}return {n:n,rows:rows,rungs:rungs,seed:seed};}
  function trace(ladder,start){var col=start,path=[{r:0,c:col}],i,row;for(i=0;i<ladder.rungs.length;i++){row=ladder.rungs[i];path.push({r:i+1,c:col,down:true});if(col<row.length&&row[col]){col+=1;path.push({r:i+1,c:col});}else if(col>0&&row[col-1]){col-=1;path.push({r:i+1,c:col});}}path.push({r:ladder.rungs.length+1,c:col,down:true});return {end:col,path:path};}
  function dest(ladder,start){return trace(ladder,start).end;}
  function ensureLadders(force){var n=state.players.length;if(!n)return;while(state.buildings.length<n)state.buildings.push("");if(state.buildings.length>n)state.buildings=state.buildings.slice(0,n);while(state.days.length<n)state.days.push((state.days.length+1)+"요일");if(state.days.length>n)state.days=state.days.slice(0,n);if(force||!state.l1||state.l1.n!==n){state.l1=makeLadder(n,10,(Date.now()%1e9)^(n*97));state.l2=makeLadder(n,10,((Date.now()*13)%1e9)^4242);}state.ready=state.buildings.every(function(b){return String(b).trim();});}
  function assignment(name){var i=state.players.indexOf(name);if(i<0||!state.l1||!state.l2)return null;return {building:state.buildings[dest(state.l1,i)]||"?",day:state.days[dest(state.l2,i)]||"?"};}
  async function loadRemote(){hashRoom();var local=readLocal();try{var res=await fetch(API+ROOM+"?t="+Date.now()+"&n="+Math.random(),{cache:"no-store",mode:"cors"});if(!res.ok)throw new Error("http "+res.status);var data=await res.json();if(data&&data.players){var remoteTime=data.updatedAt||0,localTime=(local&&local.updatedAt)||0;if(local&&localTime>remoteTime){state=Object.assign(defaultState(),local);remoteOk=false;$("netBanner").className="banner";$("netBanner").textContent="이 폰에 더 최신 값이 있어요. 다시 저장을 눌러 공유방에 올려 주세요.";saveRemote().catch(function(){});return true;}state=Object.assign(defaultState(),data);writeLocal();remoteOk=true;$("netBanner").classList.add("hidden");return true;}throw new Error("bad json");}catch(e){remoteOk=false;if(local&&local.players)state=Object.assign(defaultState(),local);$("netBanner").className="banner";$("netBanner").textContent="공유방에 아직 못 붙었어요. 카톡용 링크로 열어 주세요.";return false;}}
  async function saveRemote(){state.updatedAt=Date.now();state.rev=(state.rev||0)+1;writeLocal();var res=await fetch(API+ROOM+"?t="+Date.now(),{method:"PUT",mode:"cors",headers:{"Content-Type":"application/json","Accept":"application/json"},body:JSON.stringify(state)});if(!res.ok)throw new Error("put "+res.status);remoteOk=true;$("netBanner").classList.add("hidden");return true;}
  function beep(freq,dur,type){if(!soundOn)return;try{var ctx=beep.ctx||(beep.ctx=new (window.AudioContext||window.webkitAudioContext)());var o=ctx.createOscillator();var g=ctx.createGain();o.type=type||"triangle";o.frequency.value=freq;g.gain.value=0.05;o.connect(g);g.connect(ctx.destination);o.start();g.gain.exponentialRampToValueAtTime(0.0001,ctx.currentTime+dur);o.stop(ctx.currentTime+dur);}catch(e){}}
  function drawRing(){var total=Math.max(state.players.length,1),done=doneCount(),r=28,c=36,circ=2*Math.PI*r,p=done/total;$("ringSvg").innerHTML='<circle cx="'+c+'" cy="'+c+'" r="'+r+'" fill="none" stroke="rgba(255,255,255,.08)" stroke-width="8"/>'+'<circle cx="'+c+'" cy="'+c+'" r="'+r+'" fill="none" stroke="#ffd36b" stroke-width="8" stroke-linecap="round" stroke-dasharray="'+circ+'" stroke-dashoffset="'+(circ*(1-p))+'" transform="rotate(-90 '+c+' '+c+')"/>'+'<text x="'+c+'" y="'+(c+5)+'" text-anchor="middle" fill="#fff" font-size="14" font-weight="800">'+done+'/'+total+'</text>';$("progNum").textContent=done+" / "+total+" 완료";var wait=state.players.filter(function(p){return !(state.results[p]&&state.results[p].day);});$("progText").textContent=wait.length?("아직 "+wait.join(", ")+" 안 탐"):"전원 완료!";}
  function renderLobby(){$("subtitle").textContent=(state.title||"사다리고고")+" · 건물 + 요일";drawRing();var wait=state.players.filter(function(p){return !(state.results[p]&&state.results[p].day);});$("waitChips").innerHTML=wait.length?wait.map(function(p){return '<div class="chip wait"><span class="dot no"></span>'+avatar(p)+" "+p+"</div>";}).join(""):'<div class="chip done">전원 완료 🎉</div>';var doneHtml="";state.players.forEach(function(p){var r=state.results[p];if(!(r&&r.day))return;doneHtml+='<div class="chip done">'+avatar(p)+" "+p+" → <b>"+r.building+"</b> · "+r.day+"요일</div>";});$("doneList").innerHTML=doneHtml||'<p class="hint">아직 공개된 결과가 없어요.</p>';$("whoGrid").innerHTML=state.players.map(function(p){var r=state.results[p],done=!!(r&&r.day);return '<button class="person'+(done?" done":"")+(p===me?" me":"")+'" data-name="'+p+'"><div class="avatar">'+avatar(p)+'</div><div><strong>'+p+'</strong><small>'+(done?"완료 · 결과 보기":"아직 안 탐 · 누르고 타기")+"</small></div></button>";}).join("");if(!isReady())$("waitingSetup").classList.remove("hidden");else $("waitingSetup").classList.add("hidden");if($("shareBox"))$("shareBox").value=shareUrl();}
  function layout(n,rows,w,h){var px=36,py=46,xs=[],ys=[],i;for(i=0;i<n;i++)xs.push(px+(n===1?0:i*(w-2*px)/(n-1)));for(i=0;i<=rows+1;i++)ys.push(py+i*(h-2*py)/(rows+1));return {xs:xs,ys:ys};}
  function drawLadder(svg,ladder,tops,bottoms,highlight){var w=Math.max(520,ladder.n*86),h=420;svg.setAttribute("viewBox","0 0 "+w+" "+h);svg.setAttribute("width",w);var L=layout(ladder.n,ladder.rows,w,h),html="",i,r,y;for(i=0;i<ladder.n;i++)html+='<line x1="'+L.xs[i]+'" y1="'+L.ys[0]+'" x2="'+L.xs[i]+'" y2="'+L.ys[L.ys.length-1]+'" stroke="rgba(255,230,180,.28)" stroke-width="4" stroke-linecap="round"/>';for(r=0;r<ladder.rungs.length;r++){y=L.ys[r+1];for(i=0;i<ladder.rungs[r].length;i++){if(!ladder.rungs[r][i])continue;html+='<line x1="'+L.xs[i]+'" y1="'+y+'" x2="'+L.xs[i+1]+'" y2="'+y+'" stroke="#ffd36b" stroke-width="5" stroke-linecap="round"/>';}}for(i=0;i<ladder.n;i++){html+=label(L.xs[i],L.ys[0]-18,tops[i]||"",COLORS[i%COLORS.length]);html+=label(L.xs[i],L.ys[L.ys.length-1]+20,bottoms[i]||"","#fff");}html+='<polyline id="traceLine" fill="none" stroke="#ff4d8f" stroke-width="6" stroke-linecap="round" stroke-linejoin="round" points=""/>';html+='<circle id="traceDot" r="9" fill="#ff4d8f" stroke="#fff" stroke-width="3" cx="-20" cy="-20"/>';svg.innerHTML=html;svg._layout=L;if(highlight!=null)previewPath(svg,ladder,highlight);}
  function label(x,y,text,fill){var t=String(text||"").slice(0,6);return '<text x="'+x+'" y="'+y+'" text-anchor="middle" fill="'+fill+'" font-size="13" font-weight="800">'+escapeHtml(t)+'</text>';}
  function escapeHtml(s){return String(s).replace(/[&<>"']/g,function(c){return ({'&':'&','<':'<','>':'>','"':'"',"'":'&#39;'})[c];});}
  function pathPoints(svg,ladder,start){var L=svg._layout,tr=trace(ladder,start),pts=[];tr.path.forEach(function(p){pts.push([L.xs[p.c],L.ys[p.r]]);});return {pts:pts,end:tr.end};}
  function previewPath(svg,ladder,start){var p=pathPoints(svg,ladder,start);$("traceLine").setAttribute("points",p.pts.map(function(a){return a[0]+","+a[1];}).join(" "));var last=p.pts[p.pts.length-1];$("traceDot").setAttribute("cx",last[0]);$("traceDot").setAttribute("cy",last[1]);}
  function animatePath(svg,ladder,start,cb){var p=pathPoints(svg,ladder,start).pts,segs=[],i,dx,dy,len,tlen=0;for(i=1;i<p.length;i++){dx=p[i][0]-p[i-1][0];dy=p[i][1]-p[i-1][1];len=Math.hypot(dx,dy);segs.push({a:p[i-1],b:p[i],len:len});tlen+=len;}var startAt=performance.now(),dur=Math.min(2800,700+tlen*1.6);function frame(now){var u=Math.min(1,(now-startAt)/dur),ease=1-Math.pow(1-u,3),dist=ease*tlen,acc=0,x=p[0][0],y=p[0][1],drawn=[];drawn.push(p[0]);for(i=0;i<segs.length;i++){if(acc+segs[i].len>=dist){var f=(dist-acc)/(segs[i].len||1);x=segs[i].a[0]+(segs[i].b[0]-segs[i].a[0])*f;y=segs[i].a[1]+(segs[i].b[1]-segs[i].a[1])*f;drawn.push([x,y]);break;}acc+=segs[i].len;drawn.push(segs[i].b);x=segs[i].b[0];y=segs[i].b[1];}$("traceLine").setAttribute("points",drawn.map(function(a){return a[0]+","+a[1];}).join(" "));$("traceDot").setAttribute("cx",x);$("traceDot").setAttribute("cy",y);if(u<1)requestAnimationFrame(frame);else{beep(660,0.12);beep(880,0.16);cb&&cb();}}$("traceLine").setAttribute("points","");requestAnimationFrame(frame);beep(320,0.08,"sine");}
  var playStage=1,playName="";
  function openPlay(name){if(!isReady()){$("play").classList.add("hidden");$("result").classList.add("hidden");$("lobby").classList.remove("hidden");toast("송현이가 건물을 먼저 넣어야 해요");return;}playName=name;me=name;localStorage.setItem("sadari_me",name);var existing=state.results[name];if(existing&&existing.day){showResult(name,existing,false);return;}$("lobby").classList.add("hidden");$("result").classList.add("hidden");$("play").classList.remove("hidden");playStage=1;setupStage();}
  function setupStage(){$("playWho").textContent=avatar(playName)+" "+playName;$("btnRide").disabled=false;$("btnRide").style.opacity="1";if(playStage===1){$("playKicker").textContent="1차 · 건물 사다리";$("btnRide").textContent="건물 사다리 타기!";$("playHint").textContent="위에서 내 이름을 따라 내려가요.";drawLadder($("ladderSvg"),state.l1,state.players,state.buildings,null);}else{$("playKicker").textContent="2차 · 요일 사다리";$("btnRide").textContent="요일 사다리 타기!";$("playHint").textContent="한 번 더! 일~금 중에 내 날이 정해져요.";drawLadder($("ladderSvg"),state.l2,state.players,state.days.map(function(d){return d+"요일";}),null);}}
  async function ride(){if(riding||!isReady())return;var idx=state.players.indexOf(playName);if(idx<0)return;riding=true;$("btnRide").disabled=true;$("btnRide").style.opacity=".6";var ladder=playStage===1?state.l1:state.l2;animatePath($("ladderSvg"),ladder,idx,async function(){riding=false;if(playStage===1){var b=assignment(playName);$("playHint").textContent="도착! 건물 → "+b.building;toast("건물: "+b.building);playStage=2;setTimeout(setupStage,700);}else{var a=assignment(playName);state.results[playName]={building:a.building,day:a.day,at:Date.now()};try{await saveRemote();}catch(e){toast("결과는 이 폰에 남았어요");}burst();showResult(playName,state.results[playName],true);}});}
  function showResult(name,res,fresh){$("play").classList.add("hidden");$("lobby").classList.add("hidden");$("result").classList.remove("hidden");$("resName").textContent=avatar(name)+" "+name;$("resBld").textContent=res.building;$("resDay").textContent=res.day+"요일";$("resWhen").textContent=res.at?new Date(res.at).toLocaleString("ko-KR")+" 도착":"";if(fresh)burst();}
  function burst(){var c=$("confetti");c.classList.remove("hidden");c.width=innerWidth;c.height=innerHeight;var ctx=c.getContext("2d"),bits=[],i;for(i=0;i<80;i++)bits.push({x:innerWidth/2,y:innerHeight*0.3,vx:(Math.random()-0.5)*12,vy:Math.random()*-10-4,g:0.22+Math.random()*0.1,s:4+Math.random()*6,col:COLORS[i%COLORS.length],life:80+Math.random()*40});function tick(){ctx.clearRect(0,0,c.width,c.height);var alive=false;bits.forEach(function(b){b.vy+=b.g;b.x+=b.vx;b.y+=b.vy;b.life--;if(b.life>0){alive=true;ctx.fillStyle=b.col;ctx.fillRect(b.x,b.y,b.s,b.s*0.6);}});if(alive)requestAnimationFrame(tick);else c.classList.add("hidden");}tick();}
  function shareLink(){var url=shareUrl();if($("shareBox"))$("shareBox").value=url;copy(url);}
  function copy(text){if(navigator.clipboard&&navigator.clipboard.writeText){navigator.clipboard.writeText(text).then(function(){toast("복사됐어요. 카톡에 붙여넣기!");}).catch(function(){fallbackCopy(text);});}else fallbackCopy(text);}
  function fallbackCopy(text){var ta=document.createElement("textarea");ta.value=text;document.body.appendChild(ta);ta.select();try{document.execCommand("copy");toast("복사됐어요");}catch(e){prompt("복사",text);}document.body.removeChild(ta);}
  function fillAdmin(){$("fldTitle").value=state.title||"";$("fldPlayers").value=state.players.join(", ");$("fldDays").value=state.days.join(", ");$("fldBuildings").value=state.buildings.join(", ");$("fldPin").value=state.pin||"0326";var peek="";if(state.l1&&state.l2&&isReady()){peek="<br><b>미리보기 (관리자만)</b><br>";state.players.forEach(function(p){var a=assignment(p),st=(state.results[p]&&state.results[p].day)?" ✓":" · 미완";peek+=p+" → "+a.building+" / "+a.day+"요일"+st+"<br>";});}$("peekBox").innerHTML=peek;}
  async function saveAdmin(){var players=splitList($("fldPlayers").value),days=splitList($("fldDays").value),buildings=splitList($("fldBuildings").value);if(players.length<2){toast("사람은 2명 이상");return;}if(buildings.length!==players.length){toast("건물 수가 사람 수랑 같아야 해요");return;}if(days.length!==players.length){toast("요일 수가 사람 수랑 같아야 해요");return;}var oldResults=state.results||{};state.title=$("fldTitle").value.trim()||"사다리고고";state.pin=($("fldPin").value||"0326").trim();state.players=players;state.days=days;state.buildings=buildings;var kept={};players.forEach(function(p){if(oldResults[p])kept[p]=oldResults[p];});state.results=kept;ensureLadders(true);try{await saveRemote();toast("공유방에 저장됐어요");}catch(e){toast("이 화면엔 남았지만, 카톡 링크로 다시 열어 저장해 주세요");$("netBanner").className="banner";$("netBanner").textContent="파일로 열면 친구들과 저장이 안 이어집니다.";}fillAdmin();renderLobby();}
  $("whoGrid").addEventListener("click",function(e){var btn=e.target.closest("[data-name]");if(!btn)return;openPlay(btn.getAttribute("data-name"));});
  $("btnRide").onclick=ride;
  $("btnBackLobby").onclick=function(){$("play").classList.add("hidden");$("lobby").classList.remove("hidden");renderLobby();};
  $("btnToLobby").onclick=function(){$("result").classList.add("hidden");$("lobby").classList.remove("hidden");renderLobby();};
  $("btnReplay").onclick=function(){if(!playName)playName=me||state.players[0];$("result").classList.add("hidden");$("play").classList.remove("hidden");playStage=1;setupStage();};
  $("btnShare").onclick=shareLink;
  $("btnShare2").onclick=shareLink;
  $("btnSound").onclick=function(){soundOn=!soundOn;$("btnSound").textContent=soundOn?"🔊":"🔇";if(soundOn)beep(520,0.08);};
  $("btnAdmin").onclick=function(){$("adminModal").classList.add("on");if(isAdmin){$("adminLock").classList.add("hidden");$("adminBody").classList.remove("hidden");fillAdmin();}else{$("adminLock").classList.remove("hidden");$("adminBody").classList.add("hidden");$("pinInput").focus();}};
  $("btnCloseAdmin1").onclick=$("btnCloseAdmin2").onclick=function(){$("adminModal").classList.remove("on");};
  $("adminModal").addEventListener("click",function(e){if(e.target===$("adminModal"))$("adminModal").classList.remove("on");});
  $("btnPin").onclick=function(){if((($("pinInput").value)||"").trim()===String(state.pin||"0326")){isAdmin=true;$("adminLock").classList.add("hidden");$("adminBody").classList.remove("hidden");fillAdmin();renderLobby();toast("관리자 입장");}else toast("비밀번호가 달라요");};
  $("pinInput").addEventListener("keydown",function(e){if(e.key==="Enter")$("btnPin").click();});
  $("btnSave").onclick=saveAdmin;
  $("btnReset").onclick=async function(){if(!confirm("탄 결과만 지울까요?"))return;state.results={};try{await saveRemote();toast("결과 초기화");}catch(e){toast("이 화면만 지웠어요");}fillAdmin();renderLobby();};
  $("btnRegen").onclick=async function(){if(!confirm("사다리를 다시 섞고 결과도 지울까요?"))return;state.results={};ensureLadders(true);try{await saveRemote();toast("새 사다리!");}catch(e){toast("이 화면만 바뀌었어요");}fillAdmin();renderLobby();};
  if($("shareBox")){$("shareBox").addEventListener("focus",function(){this.select();});$("shareBox").addEventListener("click",function(){this.select();copy(this.value);});}
  document.addEventListener("visibilitychange",function(){if(!document.hidden)loadRemote().then(renderLobby);});
  setInterval(function(){if(document.hidden||riding)return;if(!$("lobby")||$("lobby").classList.contains("hidden"))return;loadRemote().then(renderLobby);},8000);
  loadRemote().then(function(){if(!state.l1&&state.buildings.some(Boolean))ensureLadders(true);renderLobby();});
})();
